#! /usr/bin/env perl
use strict;

if ($#ARGV == -1) {
    die " ERROR ww3 buildlib: must specify a caseroot input argument";
}
my ($CASEROOT) = @ARGV;
chdir "${CASEROOT}";

my $CASETOOLS       = `./xmlquery CASETOOLS      --value`;
my $SRCROOT        = `./xmlquery SRCROOT        --value`;
my $OBJROOT        = `./xmlquery OBJROOT        --value`;
my $LIBROOT        = `./xmlquery LIBROOT        --value`;
my $GMAKE_J        = `./xmlquery GMAKE_J        --value`;
my $GMAKE          = `./xmlquery GMAKE          --value`;
my $GMAKE_OPTS = `./Tools/get_standard_makefile_args`;

chdir "$OBJROOT/wav/obj";

open(file,">Filepath") or die "Could not open file Filepath to write";
print file "${CASEROOT}/SourceMods/src.ww3\n";
print file "${SRCROOT}/components/ww3/src/source\n";
print file "${SRCROOT}/components/ww3/src/cpl_share\n";
print file "${SRCROOT}/components/ww3/src/cpl_mct\n";
close(file);

my $sysmod = "$GMAKE complib -j $GMAKE_J MODEL=ww3 COMPLIB=$LIBROOT/libwav.a -f $CASETOOLS/Makefile $GMAKE_OPTS";
system($sysmod) == 0 or die "ERROR: $sysmod failed: $?\n";

exit(0);
